### ISSUE TITLE
Some problem about ngsim replay in smarts

### ISSUE THREAD

**Issue by Hc7Hs** [zbzhu99/Constrained-Policy-Optimization-Paper-List#1]
Hi zbzhu99,
I saw your issue in huawei smarts [https://github.com/huawei-noah/SMARTS/issues/407](url). In this issue, It seems that you have migrated ngsim data to smarts. I'm curious about how you do it. Can you tell me the specific implementation details？thx.

**Comment by zbzhu99** [comment]
I will upload the NGSIM related environment and code to the SMARTS repository in the near future.
If you are interested in this project, we can discuss it via email. My email address is zbzhu.yz@gmail.com.

**Comment by Hc7Hs** [comment]
OK, thx :)

**Comment by Hc7Hs** [comment]
还是直接中文沟通吧，目前我主要不知道如何将ngsim的数据集转换为smarts中sumo的rou.xml，请问大佬你当时是怎么做的？（昨天发邮件看没回复，所以只能继续再这里沟通了。。）

**Comment by zbzhu99** [comment]
我之前也花了不少时间搞这个地图转换的问题，没有找到可以自动转换的方法。后来是按照NGSIM的地图等比例用sumo的netedit地图编辑器人工画的。
在那个Github issue里面我应该是有上传了一份xml文件。

**Comment by Hc7Hs** [comment]
> 我之前也花了不少时间搞这个地图转换的问题，没有找到可以自动转换的方法。后来是按照NGSIM的地图等比例用sumo的netedit地图编辑器人工画的。
> 在那个Github issue里面我应该是有上传了一份xml文件。

那数据集里的交通流你是怎么解决的，sumo里不是需要那个rou.xml定义route或者trip吗，我看你演示里是有车辆的。

**Comment by zbzhu99** [comment]
交通流是通过smarts的scenario里面的traffic_history这个属性定义的：
https://github.com/huawei-noah/SMARTS/blob/fc2b3ccb55afd8361100c82ceafa07f6e4e13661/smarts/sstudio/types.py#L723
需要先将NGSIM的车流数据转换成一个json文件，然后在scenario.py文件里面指定。
可以参考interaction dataset的转换脚本：
https://github.com/huawei-noah/SMARTS/blob/fc2b3ccb55afd8361100c82ceafa07f6e4e13661/tools/interaction_dataset_converter.py

**Comment by Hc7Hs** [comment]
好的我研究一下，感谢大佬
